version: 1
disable_existing_loggers: False

formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - [%(message)s]"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: ./logs/app-info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: ./logs/app-errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8


root:
    level: INFO
    handlers: [ console, error_file_handler]
    propogate: yes

# loggers:
#     apis:
#         level: INFO
#         handlers: [console]
#         propogate: no

